### ISSUE TITLE
Primo Browzine service adapter - collision with prmSearchResultAvailabilityLineAfter

### ISSUE THREAD

**Issue by rmiessle** [thirdiron/browzine-discovery-service-adapters#70]
I'm attempting to integrate the Unpaywall package at https://github.com/bulib/primo-explore-bu/tree/master/packages/unpaywall into our Primo VE instance and it doesn't play well with the current code from Third Iron. It's causing a collision with prmSearchResultAvailabilityLineAfter since both packages use it. I've pasted the console error below. Have you had any other institutions with similar issues? I'm not great with Angular so it's difficult for me to hack through these sorts of things. I'm also in communication with the authors of the above package to see what thoughts they have. Thanks for any advice.

```
angular.js:14516 Error: [$compile:multidir] Multiple directives [prmSearchResultAvailabilityLineAfter, prmSearchResultAvailabilityLineAfter] asking for new/isolated scope on: <prm-search-result-availability-line-after parent-ctrl="$ctrl">
http://errors.angularjs.org/1.6.3/$compile/multidir?p0=prmSearchResultAvailabilityLineAfter&p1=&p2=prmSearchResultAvailabilityLineAfter&p3=&p4=new%2Fisolated%20scope&p5=%3Cprm-search-result-availability-line-after%20parent-ctrl%3D%22%24ctrl%22%3E
```

**Comment by johnseguin** [comment]
Hi @rmiessle Thanks for contacting us - you have good timing as this is about to become a lot easier for you with little effort!    We've had feedback from others wanting to do the same, so we're in the process of actually integrating the unpaywall responses _directly_ into the LibKey integration for a tight UI and then full coverage of availability so you won't need to have multiple links and so on that will have effectively the same data in them.  We'll have more news on this in just a few weeks and I'm happy to keep you personally posted on the availability of this enhancement for LibKey Discovery.  Let me know if you have any questions!

**Comment by rmiessle** [comment]
Do you have an update when the hosted script will be updated to include the Unpaywall feature?

**Comment by karlbecker** [comment]
Hi @rmiessle ! @johnseguin is out right now, but I'll be sure to have him respond as soon as he's back to give you an update on expected timeline. Some good news I can share: we're currently testing the functionality! We just want to make sure it's working well before we roll it out.

**Comment by johnseguin** [comment]
Hi @rmiessle -- sorry for the slow reply here but indeed Karl is right.  This should be available within just a few weeks now so will be sure to update this thread when it is!  

Additionally, if you have not done so, please subscribe to our developers newsletter here: http://eepurl.com/cTbFS1

Thanks!
John

**Comment by johnseguin** [comment]
Hi @rmiessle  - Thanks so much for your patience.  This work got delayed a little past my "few weeks" estimate to you originally but it is now out in the wild.  Our "official" documentation for the configuration of this has been updated here:

https://thirdiron.atlassian.net/wiki/spaces/BrowZineAPIDocs/pages/79200260/Ex+Libris+Primo+Integration

But if you are using the version direct from github we also updated the readme here with the new parameters you need to add:

https://github.com/thirdiron/browzine-discovery-service-adapters/blob/develop/README.md

Thanks and let us know if you have further questions!

-John

**Comment by rmiessle** [comment]
Thanks, I've implemented and it works! However I am curious as to when it elects to display the Unpaywall link. For example, this article is available via Unpaywall, but doesn't display the link:

https://gettysburg.primo.exlibrisgroup.com/permalink/01GETTYSBURG_INST/1kluq6j/proquest2103566529

**Comment by johnseguin** [comment]
Terrific!  Yes, LibKey sources are consulted first (in this case, you can see that its linking to your Nature subscription via the proxy).  This particular article from Nature is indeed (presently) OA but because its within your subscription range, LibKey picks it up.

The reason for this is that there is an inherent delay in when unpaywall's scrapers can check for availability and potential inaccuracy because of this.  If LibKey knows this is within your subscriptions, that is a more certain entitlement route so we link there first.  If that comes up empty, then we check unpaywall.  Note that LibKey also possess a large amount of OA information as well, but this particular article you cited it does not know about. :)   Thanks!
